name: Create My Awesome
description: >
  automatically generating the personal awesome list from all of the repositories you starred.
author: luob
branding:
  icon: book
  color: red
inputs:
  username:
    description: >
      You can specify to use any user's data
    default: ${{ github.repository_owner }}

  description:
    description: >
      The description for your awesome project
    default: 'A collection of awesome things.'

  repository: 
    description: >
      The owner and repository name.
    default: ${{ github.repository }}

  workflow:
    default:  ${{ github.workflow }}

  token:
    default: ${{ github.token }}
  
  targetDir:
    default: ./

runs:
  using: 'node12'
  main: 'dist/index.js'
